services:

  # バックエンド/フロントエンドリバースプロキシ - Nginx
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - guest-web
      - broadcast-sender
    networks:
      - frontend

  # フロントエンド系 - 参加者用Web
  guest-web:
    build:
      context: ./guest-web
      dockerfile: ./Dockerfile
    environment:
      VITE_API_BASE_URL: "http://localhost/api"
    networks:
      - frontend

  # フロントエンド系 - 模擬店アナウンス用
  broadcast-sender:
    build:
      context: ./broadcast-sender
      dockerfile: ./Dockerfile
    environment:
      API_BASE_URL: "http://localhost/api"
    networks:
      - frontend

  # バックエンド系 - APIサーバー
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - frontend
      - backend

  # バックエンド系 - PostgreSQL
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: sazanami
      POSTGRES_PASSWORD: sazanami
      POSTGRES_DB: sazanami
    ports:
      - "5432:5432"
    volumes:
      - ./data/api/postgres:/var/lib/postgresql/data
    networks:
      - backend

  # バックエンド系 - Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
