services:

  # バックエンド/フロントエンドリバースプロキシ - Nginx
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./htpasswd:/etc/nginx/htpasswd:ro
    depends_on:
      - api
      - guest-web
      - broadcast-sender
    networks:
      - frontend

  # フロントエンド系 - 参加者用Web
  guest-web:
    build:
      context: ./guest-web
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: "http://rca-ukuru/api"
    environment:
      VITE_API_BASE_URL: "http://rca-ukuru/api"
    networks:
      - frontend

  # フロントエンド系 - 模擬店アナウンス用
  broadcast-sender:
    build:
      context: ./broadcast-sender
      dockerfile: Dockerfile
      args:
        API_BASE_URL: "http://rca-ukuru/api"
    environment:
      API_BASE_URL: "http://rca-ukuru/api"
    networks:
      - frontend

  # フロントエンド系 - デジタルサイネージシステム
  signage:
    build:
      context: ./signage
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: "http://rca-ukuru/api"
    environment:
      VITE_API_BASE_URL: "http://rca-ukuru/api"
    networks:
      - frontend

  # バックエンド系 - APIサーバー
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        DATABASE_URL: "postgresql://sazanami:sazanami@postgres:5432/sazanami"
    environment:
      DATABASE_URL: "postgresql://sazanami:sazanami@postgres:5432/sazanami"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
    ports:
      - "3000:3000"
    entrypoint: "npm run seedAndStart"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - frontend
      - backend

  # バックエンド系 - PostgreSQL
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: sazanami
      POSTGRES_PASSWORD: sazanami
      POSTGRES_DB: sazanami
    ports:
      - "5432:5432"
    volumes:
      - ./data/api/postgres:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  # バックエンド系 - Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
